CREATE TABLE ai_agents (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category VARCHAR(100) NOT NULL,
    creator_id UUID REFERENCES user_profiles(id) ON DELETE CASCADE,
    organization_id UUID REFERENCES organizations(id) ON DELETE CASCADE,
    prompt_template TEXT NOT NULL,
    system_instructions TEXT,
    tools JSONB DEFAULT '[]',
    workflow_config JSONB DEFAULT '{}',
    file_contexts JSONB DEFAULT '[]',
    permissions VARCHAR(20) DEFAULT 'private' CHECK (permissions IN ('public',
    'organization',
    'private')),
    usage_count INTEGER DEFAULT 0,
    rating DECIMAL(2,1) DEFAULT 0.0,
    tags TEXT[],
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active',
    'inactive',
    'draft')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);