CREATE TABLE public_tools (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    icon VARCHAR(100),
    prompt_template TEXT NOT NULL,
    system_instructions TEXT,
    example_inputs JSONB DEFAULT '[]',
    tags TEXT[],
    difficulty_level VARCHAR(20) DEFAULT 'beginner' CHECK (difficulty_level IN ('beginner',
    'intermediate',
    'advanced')),
    target_audience VARCHAR(50)[] DEFAULT ARRAY['teacher',
    'student'],
    usage_count INTEGER DEFAULT 0,
    rating DECIMAL(2,1) DEFAULT 0.0,
    is_featured BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active',
    'inactive',
    'maintenance')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);